var path = require('path');

// this is suppose to run on top of args generated by yogi args,
// and it just augment that variable with more data.
exports.parse = function(args) {
    var includeDirs,
        excludeDirs,
        parsed = args.parsed;

    if (parsed['include-dirs']) {
        includeDirs = parsed['include-dirs'].split(',');
        includeDirs.forEach(function (v, k) {
            // normalizing the dirname
            includeDirs[k] = path.join('./', v);
        });
        parsed['include-dirs'] = includeDirs;
    }

    if (parsed['exclude-dirs']) {
        excludeDirs = parsed['exclude-dirs'].split(',');
        excludeDirs.forEach(function (v, k) {
            // normalizing the dirname
            excludeDirs[k] = path.join('./', v);
        });
        parsed['exclude-dirs'] = excludeDirs;
    }

    return args;
};
